(progn
  (require 'project-root)
  (global-set-key (kbd "<C-f7>") (lambda ()
                                   (interactive)
                                   (project-root-configure)
                                   ))
  (global-set-key (kbd "<S-f7>") (lambda ()
                                   (interactive)
                                   (project-root-clean)
                                   ))
  (global-set-key (kbd "<f7>") (lambda ()
                                 (interactive)
                                 (project-root-compile)
                                 ))
  (global-set-key (kbd "<f5>") (lambda ()
                                 (interactive)
                                 (project-root-run)
                                 ))
  (global-set-key (kbd "<C-f5>") (lambda ()
                                   (interactive)
                                   (project-root-debug)
                                   ))
  (global-set-key (kbd "<M-f5>") (lambda ()
                                   (interactive)
                                   (project-root-leakcheck)
                                   ))
  )
